# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78d7bd5589c39c189d791f605c048dcb1b125332da6502d1e05c461878ef7fc4e5ea9981a33586a39778bdff900a4161db6902dd99a0019cafa919972157e8ef

test:
  secret_key_base: 528af6de68d57280dda5d2f2efa3782fd3e61521855d9697f39b9b25037736629124a0c9f901f5f0aa183e76943ab8b631c1a124fb61987bfb5fd1978f3b97ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
